import type { RetrievalIntent } from "./retrieval-plan";

export type SuggestionKind = "cold_start" | "global" | "fallback";

export type SuggestionCandidate = {
  id: string;
  text: { en: string; ch: string };
  docId?: string;
  sectionId?: string;
  intent?: RetrievalIntent;
  kind: SuggestionKind;
};

/**
 * Curated suggestion bank for cold start, off-topic redirects, and trailer fallback.
 * Follow-up chips are primarily generated by the answer model via a hidden stream trailer.
 */
export const SUGGESTION_BANK: SuggestionCandidate[] = [
  // ─── Cold start (4) — only 2 shown; fixed priority in pick-suggestions ─
  {
    id: "cold-start-project",
    kind: "cold_start",
    intent: "recommend_project",
    docId: "projects-overview",
    sectionId: "where-to-start",
    text: {
      en: "What should I look at first?",
      ch: "我应该先看哪个项目？",
    },
  },
  {
    id: "cold-stack",
    kind: "cold_start",
    text: { en: "What's your tech stack?", ch: "你的技术栈是什么？" },
  },
  {
    id: "cold-who",
    kind: "cold_start",
    text: { en: "Who are you?", ch: "你是谁？" },
  },
  {
    id: "cold-quizconnect",
    kind: "cold_start",
    docId: "quizconnect",
    sectionId: "at-a-glance",
    text: { en: "Tell me about QuizConnect", ch: "介绍一下 QuizConnect" },
  },

  // ─── Global (3) — off-topic redirects ─────────────────────────────────
  {
    id: "global-projects",
    kind: "global",
    text: { en: "What projects have you built?", ch: "你做过哪些项目？" },
  },
  {
    id: "global-experience",
    kind: "global",
    text: { en: "What's your work experience?", ch: "你的工作经历是什么？" },
  },
  {
    id: "global-stack",
    kind: "global",
    text: { en: "What technologies do you use?", ch: "你常用哪些技术？" },
  },

  // ─── Fallback (1–2 per doc) — used when trailer is missing/unparseable ─
  {
    id: "fallback-bio-background",
    kind: "fallback",
    docId: "about-me",
    sectionId: "background",
    text: { en: "Tell me about your background", ch: "介绍一下你的背景" },
  },
  {
    id: "fallback-bio-education",
    kind: "fallback",
    docId: "about-me",
    sectionId: "education",
    text: { en: "Where did you study?", ch: "你在哪里读的大学？" },
  },
  {
    id: "fallback-catalog-list",
    kind: "fallback",
    docId: "projects-overview",
    sectionId: "overview",
    text: { en: "List all your projects", ch: "列出你所有的项目" },
  },
  {
    id: "fallback-catalog-github",
    kind: "fallback",
    docId: "projects-overview",
    sectionId: "other-projects-github",
    text: {
      en: "Any other projects on GitHub?",
      ch: "GitHub 上还有其他项目吗？",
    },
  },
  {
    id: "fallback-qc-websockets",
    kind: "fallback",
    docId: "quizconnect",
    sectionId: "5-architecture",
    text: {
      en: "How does real-time multiplayer work?",
      ch: "实时多人对战怎么实现的？",
    },
  },
  {
    id: "fallback-qc-hard",
    kind: "fallback",
    docId: "quizconnect",
    sectionId: "7-interesting-hard-problems-solved",
    text: {
      en: "What was the hardest part of QuizConnect?",
      ch: "QuizConnect 最难的技术点是什么？",
    },
  },
  {
    id: "fallback-fx-data-sources",
    kind: "fallback",
    docId: "nextjs-fxtrade",
    sectionId: "data-sources",
    text: {
      en: "Where does FXTrade get currency data?",
      ch: "FXTrade 的汇率数据从哪来？",
    },
  },
  {
    id: "fallback-fx-charts",
    kind: "fallback",
    docId: "nextjs-fxtrade",
    sectionId: "3-features",
    text: {
      en: "How do the FX charts work?",
      ch: "汇率图表是怎么实现的？",
    },
  },
  {
    id: "fallback-mem-konva",
    kind: "fallback",
    docId: "memories",
    sectionId: "7-interesting-hard-problems-solved",
    text: {
      en: "How does the Konva canvas editor work?",
      ch: "Konva 画布编辑器怎么实现的？",
    },
  },
  {
    id: "fallback-mem-privacy",
    kind: "fallback",
    docId: "memories",
    sectionId: "3-features",
    text: {
      en: "How does sharing and privacy work?",
      ch: "分享和隐私权限怎么做的？",
    },
  },
  {
    id: "fallback-promis-seo",
    kind: "fallback",
    docId: "promis-conveyor-chain",
    sectionId: "6-notable-technical-decisions-trade-offs",
    text: {
      en: "How did you handle SEO on Promis?",
      ch: "Promis 的 SEO 怎么做的？",
    },
  },
  {
    id: "fallback-promis-whatsapp",
    kind: "fallback",
    docId: "promis-conveyor-chain",
    sectionId: "3-features",
    text: {
      en: "How does lead capture work on Promis?",
      ch: "Promis 怎么收集客户咨询？",
    },
  },
  {
    id: "fallback-exp-mufy",
    kind: "fallback",
    docId: "work-experience",
    sectionId: "mufy-at-a-glance",
    text: { en: "What did you do at Mufy?", ch: "你在 Mufy 做了什么？" },
  },
  {
    id: "fallback-exp-product",
    kind: "fallback",
    docId: "work-experience",
    sectionId: "mufy-product",
    text: { en: "What is Mufy AI?", ch: "Mufy AI 是什么产品？" },
  },
];

export const SUGGESTION_BANK_SIZE = SUGGESTION_BANK.length;
